### ISSUE TITLE
How to limit the scaling of pinch in

### ISSUE THREAD

**Issue by jaiminpatel3** [p-sebastian/ionic2-pinchzoom#1]
Hi,

I am using it to zoom in/out the content Is there any way to limit the zoom-in. I need to limit it to certain size while doing zoom in.It should not be less than the container size. Can u help us on where I need to modify scaling?

**Comment by p-sebastian** [comment]
Hey @jaiminpatel3 , sorry for taking a while, the scaling limits are defined on ~/src/pages/home/home.ts line 91 to 96
```
if (scale > 4) {
    scale = 4;
}
if (scale < 0.5) {
    scale = 0.5;
}
```

the **4** is the max zoom-in, and the **.5** is the max zoom-out. so if you want to increase the max zoom-in it would loook like

```
if (scale > 5) {
    scale = 5;
}
if (scale < 0.5) {
    scale = 0.5;
}
```

As for the boundaries limits, they are defined by the variables **max_x** and **max_y**, on the function **setCoor()/ line #122** it makes sure that it doesn't go past that point. So you might wanna mess around with it there.

**Comment by jaiminpatel3** [comment]
Hello sebastianm, Thanks for a reply.
